spring:
  redis:
    host: c88-redis
    port: 6379
    password: 78769184-fc2b-4ea3-a1bd-cc54be2fa5ea
    database: 0
  rabbitmq:
    host: c88-rabbitmq
    port: 5672
    username: default_user_Osv3MoxUtXtNvQmXeRN
    password: SGqGu_iWdeCQ2Liol0YjerADxrOASc3y
logging:
  level:
    org:
      springframework:
        security: debug
    com:
      c88:
        admin:
          api:
            OAuthClientFeignClient: DEBUG
#hystrix
feign:
  circuitbreaker:
    enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    persist-authorization: true
  cache:
    disabled: false
  pre-loading-enabled: true