spring:
  redis:
    host: c88-redis
    port: 6379
    password: 4c55365c-009b-477b-ae47-07f15947c164
    database: 0
  rabbitmq:
    host: c88-rabbitmq
    port: 5672
    username: default_user_HsMJ5kUM_Xl0xkwKC9x
    password: mhXn1tDjBk7WIbzW8IGbf8vABeWWGoDM
logging:
  level:
    org:
      springframework:
        security: debug
    com:
      c88:
        admin:
          api:
            OAuthClientFeignClient: DEBUG
#hystrix
feign:
  circuitbreaker:
    enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    persist-authorization: true
  cache:
    disabled: false
  pre-loading-enabled: true